export interface FormTheme {
  id: string;
  name: string;
  category: 'Modern' | 'Glassmorphism' | 'Neobrutalism' | 'Minimalist' | 'Corporate' | 'Cyberpunk';
  variables: Record<string, string>;
}

export const FORM_THEMES: FormTheme[] = [
  // --- GLASSMORPHISM ---
  {
    id: 'glass-ethereal',
    name: 'Ethereal Architect (Default)',
    category: 'Glassmorphism',
    variables: {
      '--t-bg': 'radial-gradient(circle at 50% -20%, #2b1836, #0a0a0f)',
      '--t-surface': 'rgba(255, 255, 255, 0.03)',
      '--t-surface-high': 'rgba(255, 255, 255, 0.07)',
      '--t-border': 'rgba(255, 255, 255, 0.1)',
      '--t-border-focus': '#d398fe',
      '--t-text': '#ffffff',
      '--t-text-muted': 'rgba(255, 255, 255, 0.5)',
      '--t-primary': '#d398fe',
      '--t-primary-hover': '#c288ed',
      '--t-on-primary': '#39005d',
      '--t-radius-card': '24px',
      '--t-radius-input': '12px',
      '--t-shadow': '0 20px 40px rgba(0,0,0,0.5)',
      '--t-blur': '20px',
      '--t-font': '"Space Grotesk", sans-serif',
      '--t-input-border': '1px solid var(--t-border)',
    }
  },
  {
    id: 'glass-ocean',
    name: 'Deep Ocean Glass',
    category: 'Glassmorphism',
    variables: {
      '--t-bg': 'linear-gradient(135deg, #0f2027, #203a43, #2c5364)',
      '--t-surface': 'rgba(255, 255, 255, 0.05)',
      '--t-surface-high': 'rgba(255, 255, 255, 0.1)',
      '--t-border': 'rgba(255, 255, 255, 0.15)',
      '--t-border-focus': '#00d2ff',
      '--t-text': '#ffffff',
      '--t-text-muted': 'rgba(255, 255, 255, 0.6)',
      '--t-primary': '#00d2ff',
      '--t-primary-hover': '#3a7bd5',
      '--t-on-primary': '#000000',
      '--t-radius-card': '20px',
      '--t-radius-input': '10px',
      '--t-shadow': '0 8px 32px rgba(0,0,0,0.3)',
      '--t-blur': '16px',
      '--t-font': '"Inter", sans-serif',
      '--t-input-border': '1px solid var(--t-border)',
    }
  },
  {
    id: 'glass-frost',
    name: 'Arctic Frost',
    category: 'Glassmorphism',
    variables: {
      '--t-bg': '#e0eafc',
      '--t-surface': 'rgba(255, 255, 255, 0.6)',
      '--t-surface-high': 'rgba(255, 255, 255, 0.8)',
      '--t-border': 'rgba(255, 255, 255, 0.5)',
      '--t-border-focus': '#3b82f6',
      '--t-text': '#1e293b',
      '--t-text-muted': '#64748b',
      '--t-primary': '#3b82f6',
      '--t-primary-hover': '#2563eb',
      '--t-on-primary': '#ffffff',
      '--t-radius-card': '30px',
      '--t-radius-input': '16px',
      '--t-shadow': '0 8px 32px rgba(31, 38, 135, 0.1)',
      '--t-blur': '20px',
      '--t-font': '"Manrope", sans-serif',
      '--t-input-border': '1px solid var(--t-border)',
    }
  },

  // --- NEOBRUTALISM ---
  {
    id: 'neo-yellow',
    name: 'Warning Yellow',
    category: 'Neobrutalism',
    variables: {
      '--t-bg': '#fde047',
      '--t-surface': '#ffffff',
      '--t-surface-high': '#ffffff',
      '--t-border': '#000000',
      '--t-border-focus': '#000000',
      '--t-text': '#000000',
      '--t-text-muted': '#444444',
      '--t-primary': '#ef4444',
      '--t-primary-hover': '#dc2626',
      '--t-on-primary': '#ffffff',
      '--t-radius-card': '0px',
      '--t-radius-input': '0px',
      '--t-shadow': '8px 8px 0px #000000',
      '--t-blur': '0px',
      '--t-font': '"Space Grotesk", sans-serif',
      '--t-input-border': '3px solid #000000',
    }
  },
  {
    id: 'neo-pink',
    name: 'Bubblegum Brutal',
    category: 'Neobrutalism',
    variables: {
      '--t-bg': '#f9a8d4',
      '--t-surface': '#fdf2f8',
      '--t-surface-high': '#ffffff',
      '--t-border': '#000000',
      '--t-border-focus': '#000000',
      '--t-text': '#000000',
      '--t-text-muted': '#555555',
      '--t-primary': '#3b82f6',
      '--t-primary-hover': '#2563eb',
      '--t-on-primary': '#ffffff',
      '--t-radius-card': '8px',
      '--t-radius-input': '4px',
      '--t-shadow': '6px 6px 0px #000000',
      '--t-blur': '0px',
      '--t-font': '"Courier New", monospace',
      '--t-input-border': '2px solid #000000',
    }
  },
  {
    id: 'neo-mint',
    name: 'Mint Condition',
    category: 'Neobrutalism',
    variables: {
      '--t-bg': '#6ee7b7',
      '--t-surface': '#ffffff',
      '--t-surface-high': '#ffffff',
      '--t-border': '#1e293b',
      '--t-border-focus': '#1e293b',
      '--t-text': '#0f172a',
      '--t-text-muted': '#334155',
      '--t-primary': '#8b5cf6',
      '--t-primary-hover': '#7c3aed',
      '--t-on-primary': '#ffffff',
      '--t-radius-card': '12px',
      '--t-radius-input': '8px',
      '--t-shadow': '5px 5px 0px #1e293b',
      '--t-blur': '0px',
      '--t-font': '"Inter", sans-serif',
      '--t-input-border': '2px solid var(--t-border)',
    }
  },
  {
    id: 'neo-mono',
    name: 'High Contrast Mono',
    category: 'Neobrutalism',
    variables: {
      '--t-bg': '#ffffff',
      '--t-surface': '#ffffff',
      '--t-surface-high': '#f8fafc',
      '--t-border': '#000000',
      '--t-border-focus': '#000000',
      '--t-text': '#000000',
      '--t-text-muted': '#64748b',
      '--t-primary': '#000000',
      '--t-primary-hover': '#333333',
      '--t-on-primary': '#ffffff',
      '--t-radius-card': '0px',
      '--t-radius-input': '0px',
      '--t-shadow': '10px 10px 0px #000000',
      '--t-blur': '0px',
      '--t-font': '"Inter", sans-serif',
      '--t-input-border': '4px solid #000000',
    }
  },

  // --- CYBERPUNK ---
  {
    id: 'cyber-neon',
    name: 'Neon Grid',
    category: 'Cyberpunk',
    variables: {
      '--t-bg': '#09090b',
      '--t-surface': '#18181b',
      '--t-surface-high': '#27272a',
      '--t-border': '#3f3f46',
      '--t-border-focus': '#22d3ee',
      '--t-text': '#e4e4e7',
      '--t-text-muted': '#a1a1aa',
      '--t-primary': '#f0abfc',
      '--t-primary-hover': '#e879f9',
      '--t-on-primary': '#000000',
      '--t-radius-card': '0px',
      '--t-radius-input': '0px',
      '--t-shadow': '0 0 15px rgba(34, 211, 238, 0.4)',
      '--t-blur': '0px',
      '--t-font': '"Courier New", monospace',
      '--t-input-border': '1px solid var(--t-border)',
    }
  },
  {
    id: 'cyber-matrix',
    name: 'Terminal Green',
    category: 'Cyberpunk',
    variables: {
      '--t-bg': '#000000',
      '--t-surface': '#001a00',
      '--t-surface-high': '#003300',
      '--t-border': '#00ff00',
      '--t-border-focus': '#00ff00',
      '--t-text': '#00ff00',
      '--t-text-muted': '#008800',
      '--t-primary': '#00ff00',
      '--t-primary-hover': '#00cc00',
      '--t-on-primary': '#000000',
      '--t-radius-card': '0px',
      '--t-radius-input': '0px',
      '--t-shadow': '0 0 10px #00ff00',
      '--t-blur': '0px',
      '--t-font': 'monospace',
      '--t-input-border': '1px dashed #00ff00',
    }
  },
  {
    id: 'cyber-outrun',
    name: 'Outrun Sunset',
    category: 'Cyberpunk',
    variables: {
      '--t-bg': 'linear-gradient(to bottom, #2b1055, #7597de)',
      '--t-surface': '#170b3b',
      '--t-surface-high': '#24135e',
      '--t-border': '#ff007f',
      '--t-border-focus': '#00f3ff',
      '--t-text': '#ffffff',
      '--t-text-muted': '#b3a2d4',
      '--t-primary': '#ff007f',
      '--t-primary-hover': '#e60073',
      '--t-on-primary': '#ffffff',
      '--t-radius-card': '4px',
      '--t-radius-input': '0px',
      '--t-shadow': '0 0 20px rgba(255, 0, 127, 0.6)',
      '--t-blur': '0px',
      '--t-font': '"Inter", sans-serif',
      '--t-input-border': '1px solid var(--t-border)',
    }
  },

  // --- MINIMALIST ---
  {
    id: 'min-light',
    name: 'Clean Light',
    category: 'Minimalist',
    variables: {
      '--t-bg': '#fafafa',
      '--t-surface': '#ffffff',
      '--t-surface-high': '#ffffff',
      '--t-border': '#e5e5e5',
      '--t-border-focus': '#000000',
      '--t-text': '#171717',
      '--t-text-muted': '#737373',
      '--t-primary': '#000000',
      '--t-primary-hover': '#404040',
      '--t-on-primary': '#ffffff',
      '--t-radius-card': '16px',
      '--t-radius-input': '8px',
      '--t-shadow': '0 4px 20px rgba(0,0,0,0.03)',
      '--t-blur': '0px',
      '--t-font': '"Inter", sans-serif',
      '--t-input-border': '1px solid var(--t-border)',
    }
  },
  {
    id: 'min-dark',
    name: 'Clean Dark',
    category: 'Minimalist',
    variables: {
      '--t-bg': '#0a0a0a',
      '--t-surface': '#171717',
      '--t-surface-high': '#262626',
      '--t-border': '#404040',
      '--t-border-focus': '#ffffff',
      '--t-text': '#fafafa',
      '--t-text-muted': '#a3a3a3',
      '--t-primary': '#ffffff',
      '--t-primary-hover': '#d4d4d4',
      '--t-on-primary': '#000000',
      '--t-radius-card': '16px',
      '--t-radius-input': '8px',
      '--t-shadow': '0 4px 20px rgba(0,0,0,0.5)',
      '--t-blur': '0px',
      '--t-font': '"Inter", sans-serif',
      '--t-input-border': '1px solid var(--t-border)',
    }
  },
  {
    id: 'min-paper',
    name: 'Paper Texture',
    category: 'Minimalist',
    variables: {
      '--t-bg': '#f4f1ea',
      '--t-surface': '#fffdf8',
      '--t-surface-high': '#ffffff',
      '--t-border': '#d8d4cb',
      '--t-border-focus': '#8b7d6b',
      '--t-text': '#3e3a35',
      '--t-text-muted': '#8f887b',
      '--t-primary': '#665c51',
      '--t-primary-hover': '#4e463d',
      '--t-on-primary': '#ffffff',
      '--t-radius-card': '4px',
      '--t-radius-input': '2px',
      '--t-shadow': '0 2px 10px rgba(0,0,0,0.04)',
      '--t-blur': '0px',
      '--t-font': '"Georgia", serif',
      '--t-input-border': '1px solid var(--t-border)',
    }
  },
  {
    id: 'min-clay',
    name: 'Clay Soft',
    category: 'Minimalist',
    variables: {
      '--t-bg': '#e5e7eb',
      '--t-surface': '#f3f4f6',
      '--t-surface-high': '#ffffff',
      '--t-border': '#d1d5db',
      '--t-border-focus': '#6b7280',
      '--t-text': '#374151',
      '--t-text-muted': '#9ca3af',
      '--t-primary': '#4b5563',
      '--t-primary-hover': '#374151',
      '--t-on-primary': '#ffffff',
      '--t-radius-card': '24px',
      '--t-radius-input': '12px',
      '--t-shadow': 'inset 0 2px 4px 0 rgba(255,255,255,0.8), 0 4px 10px rgba(0,0,0,0.05)',
      '--t-blur': '0px',
      '--t-font': '"Manrope", sans-serif',
      '--t-input-border': '1px solid var(--t-border)',
    }
  },

  // --- CORPORATE ---
  {
    id: 'corp-blue',
    name: 'Enterprise Blue',
    category: 'Corporate',
    variables: {
      '--t-bg': '#f8fafc',
      '--t-surface': '#ffffff',
      '--t-surface-high': '#ffffff',
      '--t-border': '#cbd5e1',
      '--t-border-focus': '#0f172a',
      '--t-text': '#0f172a',
      '--t-text-muted': '#64748b',
      '--t-primary': '#2563eb',
      '--t-primary-hover': '#1d4ed8',
      '--t-on-primary': '#ffffff',
      '--t-radius-card': '8px',
      '--t-radius-input': '4px',
      '--t-shadow': '0 1px 3px rgba(0,0,0,0.1)',
      '--t-blur': '0px',
      '--t-font': '"Inter", sans-serif',
      '--t-input-border': '1px solid var(--t-border)',
    }
  },
  {
    id: 'corp-slate',
    name: 'Executive Slate',
    category: 'Corporate',
    variables: {
      '--t-bg': '#f1f5f9',
      '--t-surface': '#ffffff',
      '--t-surface-high': '#ffffff',
      '--t-border': '#94a3b8',
      '--t-border-focus': '#334155',
      '--t-text': '#334155',
      '--t-text-muted': '#94a3b8',
      '--t-primary': '#475569',
      '--t-primary-hover': '#334155',
      '--t-on-primary': '#ffffff',
      '--t-radius-card': '6px',
      '--t-radius-input': '6px',
      '--t-shadow': '0 2px 5px rgba(0,0,0,0.05)',
      '--t-blur': '0px',
      '--t-font': '"Inter", sans-serif',
      '--t-input-border': '1px solid var(--t-border)',
    }
  },
  {
    id: 'corp-emerald',
    name: 'Healthcare Emerald',
    category: 'Corporate',
    variables: {
      '--t-bg': '#f0fdf4',
      '--t-surface': '#ffffff',
      '--t-surface-high': '#ffffff',
      '--t-border': '#bbf7d0',
      '--t-border-focus': '#166534',
      '--t-text': '#14532d',
      '--t-text-muted': '#4ade80',
      '--t-primary': '#10b981',
      '--t-primary-hover': '#059669',
      '--t-on-primary': '#ffffff',
      '--t-radius-card': '12px',
      '--t-radius-input': '8px',
      '--t-shadow': '0 4px 6px -1px rgba(0,0,0,0.05)',
      '--t-blur': '0px',
      '--t-font': '"Inter", sans-serif',
      '--t-input-border': '1px solid var(--t-border)',
    }
  },
  {
    id: 'corp-indigo',
    name: 'Fintech Indigo',
    category: 'Corporate',
    variables: {
      '--t-bg': '#eef2ff',
      '--t-surface': '#ffffff',
      '--t-surface-high': '#ffffff',
      '--t-border': '#c7d2fe',
      '--t-border-focus': '#4338ca',
      '--t-text': '#312e81',
      '--t-text-muted': '#818cf8',
      '--t-primary': '#4f46e5',
      '--t-primary-hover': '#4338ca',
      '--t-on-primary': '#ffffff',
      '--t-radius-card': '16px',
      '--t-radius-input': '12px',
      '--t-shadow': '0 10px 15px -3px rgba(0,0,0,0.05)',
      '--t-blur': '0px',
      '--t-font': '"Manrope", sans-serif',
      '--t-input-border': '1px solid var(--t-border)',
    }
  },

  // --- MODERN ---
  {
    id: 'modern-sunset',
    name: 'Sunset Gradient',
    category: 'Modern',
    variables: {
      '--t-bg': '#fff1f2',
      '--t-surface': '#ffffff',
      '--t-surface-high': '#ffffff',
      '--t-border': '#fecdd3',
      '--t-border-focus': '#f43f5e',
      '--t-text': '#881337',
      '--t-text-muted': '#fb7185',
      '--t-primary': '#f43f5e',
      '--t-primary-hover': '#e11d48',
      '--t-on-primary': '#ffffff',
      '--t-radius-card': '24px',
      '--t-radius-input': '9999px',
      '--t-shadow': '0 10px 25px rgba(244, 63, 94, 0.1)',
      '--t-blur': '0px',
      '--t-font': '"Space Grotesk", sans-serif',
      '--t-input-border': '1px solid var(--t-border)',
    }
  },
  {
    id: 'modern-lavender',
    name: 'Lavender Tech',
    category: 'Modern',
    variables: {
      '--t-bg': '#faf5ff',
      '--t-surface': '#ffffff',
      '--t-surface-high': '#ffffff',
      '--t-border': '#e9d5ff',
      '--t-border-focus': '#9333ea',
      '--t-text': '#4c1d95',
      '--t-text-muted': '#a855f7',
      '--t-primary': '#a855f7',
      '--t-primary-hover': '#9333ea',
      '--t-on-primary': '#ffffff',
      '--t-radius-card': '32px',
      '--t-radius-input': '16px',
      '--t-shadow': '0 20px 25px -5px rgba(168, 85, 247, 0.1)',
      '--t-blur': '0px',
      '--t-font': '"Inter", sans-serif',
      '--t-input-border': '1px solid var(--t-border)',
    }
  },
  {
    id: 'modern-earth',
    name: 'Earth Tones',
    category: 'Modern',
    variables: {
      '--t-bg': '#fefce8',
      '--t-surface': '#ffffff',
      '--t-surface-high': '#ffffff',
      '--t-border': '#fef08a',
      '--t-border-focus': '#ca8a04',
      '--t-text': '#713f12',
      '--t-text-muted': '#a16207',
      '--t-primary': '#eab308',
      '--t-primary-hover': '#ca8a04',
      '--t-on-primary': '#ffffff',
      '--t-radius-card': '20px',
      '--t-radius-input': '10px',
      '--t-shadow': '0 4px 6px rgba(234, 179, 8, 0.1)',
      '--t-blur': '0px',
      '--t-font': '"Space Grotesk", sans-serif',
      '--t-input-border': '1px solid var(--t-border)',
    }
  }
];
